congestion:
    tax:
      exemptions: Motorcycle,Tractor,Emergency,Diplomat,Foreign,Military
      rules:
        - timeRange: "06:00-06:29"
          amount: 8
        - timeRange: "06:30-06:59"
          amount: 13
        - timeRange: "07:00-07:59"
          amount: 18
        - timeRange: "08:00-08:29"
          amount: 13
        - timeRange: "08:30-14:59"
          amount: 8
        - timeRange: "15:00-15:29"
          amount: 13
        - timeRange: "15:30-16:59"
          amount: 18
        - timeRange: "17:00-17:59"
          amount: 13
        - timeRange: "18:00-18:29"
          amount: 8
        - timeRange: "18:30-05:59"
          amount: 0
